# Generated by Django 3.0.7 on 2020-07-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='imgae_url',
            new_name='image_url',
        ),
        migrations.DeleteModel(
            name='Tweet2',
        ),
    ]
