# Generated by Django 3.0.7 on 2020-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
