# Generated by Django 3.0.7 on 2020-07-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20200707_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
