# Generated by Django 3.0.8 on 2020-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20200707_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
